-- ============================================================================
-- NuraVision · 0013 · Tienda, pedidos y newsletter
-- ============================================================================
-- Agrega la venta de productos del Diseño 1 «Tienda»:
--
--   · productos                  catalogo publico, gestionado por el personal.
--   · pedidos / pedido_items     compras, con o sin cuenta (igual que reservas).
--   · suscripciones_newsletter   correos del footer.
--   · crear_pedido()             UNICA via para crear un pedido.
--   · suscribir_newsletter()     UNICA via para suscribirse.
--
-- Es aditiva: no modifica ninguna tabla anterior y se puede reaplicar (usa
-- "if not exists" y "on conflict do nothing").
--
-- POR QUE LOS PEDIDOS SE CREAN CON UNA FUNCION Y NO CON INSERT:
-- Con un INSERT abierto, el total lo fijaria el navegador, y cualquiera con la
-- anon key podria comprar el kit a $1. La funcion recibe solo productos y
-- cantidades, y calcula precios, despacho y descuentos leyendo la base. Por eso
-- `pedidos` y `pedido_items` no conceden INSERT a nadie.
--
-- Las reglas de dinero viven aqui y tienen un espejo en
-- frontend/src/modules/pedidos/domain/pedido.reglas.ts, que solo sirve para
-- mostrar el resumen antes de pagar. Si cambias una, cambia la otra: si no, el
-- resumen y lo cobrado no coincidirian.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Tipos
-- ----------------------------------------------------------------------------
-- Como con estado_reserva: se crean solo si faltan, para poder reaplicar.
do $$
begin
  if not exists (select 1 from pg_type where typname = 'entrega_pedido') then
    create type public.entrega_pedido as enum ('despacho', 'retiro', 'cita');
  end if;
  if not exists (select 1 from pg_type where typname = 'metodo_pago_pedido') then
    create type public.metodo_pago_pedido as enum ('webpay', 'transferencia', 'estudio');
  end if;
  if not exists (select 1 from pg_type where typname = 'estado_pedido') then
    create type public.estado_pedido as enum (
      'pendiente_pago',
      'pagado',
      'preparando',
      'listo',
      'despachado',
      'entregado',
      'cancelado'
    );
  end if;
end
$$;

-- ----------------------------------------------------------------------------
-- productos
-- ----------------------------------------------------------------------------
-- ⚠  EN EL PROYECTO ACTUAL `productos` YA EXISTIA, creada a mano fuera de
--    migrations/ (como paso con `perfiles`, ver 0010), con otra forma: id,
--    nombre, categoria, precio, descripcion, stock y activo. Ninguna parte del
--    codigo la usaba. Por eso esta seccion no asume nada:
--
--      1. Si la tabla no existe, la crea completa.
--      2. Si existe, le AGREGA las columnas que faltan. No borra ni cambia el
--         tipo de ninguna columna previa.
--      3. Las filas previas reciben un slug derivado del nombre y su id.
--      4. Los checks se agregan NOT VALID: rigen para lo que se escriba desde
--         ahora, sin rechazar la migracion por filas antiguas que no los
--         cumplan. El frontend ignora las filas con categoria desconocida.
create table if not exists public.productos (
  id               bigint generated by default as identity primary key,
  nombre           text    not null,
  categoria        text    not null,
  -- Pesos chilenos enteros: el CLP no tiene decimales.
  precio           integer not null,
  descripcion      text    not null default '',
  -- NULL = sin control de stock. Con valor, crear_pedido lo descuenta.
  stock            integer,
  activo           boolean not null default true
);

-- Lo que viaja en la URL (/tienda/aceite-de-cuticula-nura) y en el carrito.
alter table public.productos add column if not exists slug text;
-- "15 ml", "Aceite + crema + lima". Texto libre de presentacion.
alter table public.productos add column if not exists tamano text not null default '';
-- Precio tachado. NULL = no hay precio anterior que mostrar.
alter table public.productos add column if not exists precio_anterior integer;
alter table public.productos add column if not exists imagen_url text;
alter table public.productos add column if not exists insignia text;
-- Servicio en que se usa. Sin servicio (gift card) queda NULL.
alter table public.productos add column if not exists servicio_id bigint
  references public.servicios (id) on delete set null;
alter table public.productos add column if not exists modo_uso text not null default '';
alter table public.productos add column if not exists ingredientes text not null default '';
-- Orden en el catalogo. Menor primero.
alter table public.productos add column if not exists orden integer not null default 0;
alter table public.productos add column if not exists creado_en timestamptz not null default now();

-- Filas previas sin slug: nombre en minusculas, sin tildes ni simbolos, mas el
-- id para que dos nombres iguales no choquen.
update public.productos
   set slug = trim(both '-' from regexp_replace(
                translate(lower(coalesce(nombre, 'producto')), 'áéíóúüñ', 'aeiouun'),
                '[^a-z0-9]+', '-', 'g'))
              || '-' || id::text
 where slug is null;

alter table public.productos alter column slug set not null;
create unique index if not exists productos_slug_key on public.productos (slug);

alter table public.productos drop constraint if exists productos_categoria_valida;
alter table public.productos add constraint productos_categoria_valida
  check (categoria in ('unas_manos', 'cabello', 'piel', 'kits', 'gift_cards')) not valid;
alter table public.productos drop constraint if exists productos_insignia_valida;
alter table public.productos add constraint productos_insignia_valida
  check (insignia is null or insignia in ('mas_vendido', 'nuevo', 'kit')) not valid;
alter table public.productos drop constraint if exists productos_precio_positivo;
alter table public.productos add constraint productos_precio_positivo
  check (precio > 0) not valid;
alter table public.productos drop constraint if exists productos_precio_anterior_mayor;
alter table public.productos add constraint productos_precio_anterior_mayor
  check (precio_anterior is null or precio_anterior > precio) not valid;
alter table public.productos drop constraint if exists productos_stock_no_negativo;
alter table public.productos add constraint productos_stock_no_negativo
  check (stock is null or stock >= 0) not valid;
alter table public.productos drop constraint if exists productos_slug_formato;
alter table public.productos add constraint productos_slug_formato
  check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$') not valid;

comment on table public.productos is
  'Productos de la tienda. Solo los activos se ofrecen.';
comment on column public.productos.categoria is
  'unas_manos | cabello | piel | kits | gift_cards. Ids del dominio, no etiquetas.';
comment on column public.productos.servicio_id is
  'Servicio donde el estudio usa el producto. Alimenta «Lo usamos en», el upsell '
  'de Nuva y el descuento del combo.';
comment on column public.productos.stock is
  'NULL = sin control de stock. Con valor, crear_pedido lo descuenta.';

create index if not exists productos_activos_idx
  on public.productos (orden, nombre)
  where activo;

-- ----------------------------------------------------------------------------
-- pedidos
-- ----------------------------------------------------------------------------
create table if not exists public.pedidos (
  id               bigint generated by default as identity primary key,
  -- Lo que identifica el pedido para quien compro sin cuenta.
  codigo           text not null unique,
  -- Sin FK a perfiles, por la misma razon que reservas.cliente_id (0003).
  cliente_id       uuid,
  cliente_nombre   text not null,
  cliente_email    text not null,
  cliente_telefono text,
  entrega          public.entrega_pedido not null,
  direccion        text,
  comuna           text,
  -- Reserva en la que se entrega, solo con entrega = 'cita'.
  reserva_id       bigint references public.reservas (id) on delete set null,
  metodo_pago      public.metodo_pago_pedido not null,
  estado           public.estado_pedido not null default 'pendiente_pago',
  subtotal         integer not null,
  costo_envio      integer not null default 0,
  descuento        integer not null default 0,
  total            integer not null,
  creado_en        timestamptz not null default now(),
  actualizado_en   timestamptz not null default now(),

  constraint pedidos_montos_validos
    check (subtotal > 0 and costo_envio >= 0 and descuento >= 0
           and total = subtotal + costo_envio - descuento),
  constraint pedidos_direccion_si_despacho
    check (entrega <> 'despacho'
           or (nullif(btrim(direccion), '') is not null
               and nullif(btrim(comuna), '') is not null)),
  constraint pedidos_reserva_si_cita
    check (entrega <> 'cita' or reserva_id is not null),
  constraint pedidos_pago_en_estudio_sin_despacho
    check (not (metodo_pago = 'estudio' and entrega = 'despacho'))
);

comment on table public.pedidos is
  'Compras de la tienda. Se crean solo con crear_pedido(); admite invitadas.';
comment on column public.pedidos.total is
  'Calculado por crear_pedido() con los precios de la base, nunca por el navegador.';

create index if not exists pedidos_cliente_idx
  on public.pedidos (cliente_id, creado_en desc)
  where cliente_id is not null;
create index if not exists pedidos_creados_idx
  on public.pedidos (creado_en desc);

-- ----------------------------------------------------------------------------
-- pedido_items
-- ----------------------------------------------------------------------------
-- nombre y precio_unitario son una COPIA, como reservas.detalles_extra: si el
-- estudio cambia el precio o borra el producto, el pedido conserva lo cobrado.
create table if not exists public.pedido_items (
  id               bigint generated by default as identity primary key,
  pedido_id        bigint not null references public.pedidos (id) on delete cascade,
  producto_id      bigint references public.productos (id) on delete set null,
  nombre           text    not null,
  precio_unitario  integer not null,
  cantidad         integer not null,
  descuento        integer not null default 0,

  constraint pedido_items_cantidad_valida check (cantidad between 1 and 20),
  constraint pedido_items_precio_positivo check (precio_unitario > 0),
  constraint pedido_items_descuento_valido check (descuento >= 0)
);

create index if not exists pedido_items_pedido_idx
  on public.pedido_items (pedido_id);

-- ----------------------------------------------------------------------------
-- suscripciones_newsletter
-- ----------------------------------------------------------------------------
create table if not exists public.suscripciones_newsletter (
  email      text primary key,
  creado_en  timestamptz not null default now(),

  constraint newsletter_email_normalizado check (email = lower(btrim(email))),
  constraint newsletter_email_formato check (email ~ '^[^@\s]+@[^@\s]+\.[^@\s]+$')
);

comment on table public.suscripciones_newsletter is
  'Correos suscritos desde el footer. Solo se escribe con suscribir_newsletter().';

-- ----------------------------------------------------------------------------
-- RLS
-- ----------------------------------------------------------------------------
alter table public.productos                enable row level security;
alter table public.pedidos                  enable row level security;
alter table public.pedido_items             enable row level security;
alter table public.suscripciones_newsletter enable row level security;

-- productos: lectura publica, como servicios. El filtro de activo lo hace la
-- consulta, para que el panel pueda ver los inactivos (mismo criterio que 0002).
drop policy if exists "lectura publica de productos" on public.productos;
create policy "lectura publica de productos"
  on public.productos for select
  to anon, authenticated
  using (true);

drop policy if exists "El personal gestiona los productos" on public.productos;
create policy "El personal gestiona los productos"
  on public.productos for all
  to authenticated
  using (public.es_staff())
  with check (public.es_staff());

-- pedidos: cada cuenta lee los suyos; el personal lee y gestiona todos.
drop policy if exists "Lectura de pedidos propios" on public.pedidos;
create policy "Lectura de pedidos propios"
  on public.pedidos for select
  to authenticated
  using (cliente_id = auth.uid());

drop policy if exists "Lectura de pedidos por el personal" on public.pedidos;
create policy "Lectura de pedidos por el personal"
  on public.pedidos for select
  to authenticated
  using (public.es_staff());

drop policy if exists "Gestion de pedidos por el personal" on public.pedidos;
create policy "Gestion de pedidos por el personal"
  on public.pedidos for update
  to authenticated
  using (public.es_staff())
  with check (public.es_staff());

-- pedido_items: visibles si el pedido lo es.
drop policy if exists "Lectura de items de pedidos visibles" on public.pedido_items;
create policy "Lectura de items de pedidos visibles"
  on public.pedido_items for select
  to authenticated
  using (
    exists (
      select 1
      from public.pedidos p
      where p.id = pedido_id
        and (p.cliente_id = auth.uid() or public.es_staff())
    )
  );

-- suscripciones_newsletter: sin politicas a proposito. Nadie la lee desde el
-- navegador; se escribe solo con la funcion de abajo.

-- ----------------------------------------------------------------------------
-- Permisos de tabla
-- ----------------------------------------------------------------------------
grant usage on schema public to anon, authenticated;

grant select on public.productos to anon, authenticated;
revoke insert, update, delete on public.productos from anon;
grant insert, update, delete on public.productos to authenticated;

-- Sin INSERT ni DELETE para nadie: los pedidos nacen en crear_pedido() y no se
-- borran, se cancelan. El personal solo cambia el estado.
revoke all on public.pedidos from anon;
revoke insert, delete on public.pedidos from authenticated;
grant select on public.pedidos to authenticated;
grant update (estado, actualizado_en) on public.pedidos to authenticated;

revoke all on public.pedido_items from anon;
revoke insert, update, delete on public.pedido_items from authenticated;
grant select on public.pedido_items to authenticated;

revoke all on public.suscripciones_newsletter from anon, authenticated;

-- ----------------------------------------------------------------------------
-- crear_pedido
-- ----------------------------------------------------------------------------
-- security definer: corre con los permisos del dueño para poder insertar en
-- tablas que el navegador no puede escribir. Todo lo que entra se valida aqui,
-- porque esta funcion es la unica puerta.
--
-- p_items: [{"slug": "aceite-de-cuticula-nura", "cantidad": 2}, ...]
--
-- Los errores pensados para la clienta usan errcode P0001 y un mensaje en
-- español listo para mostrar.
create or replace function public.crear_pedido(
  p_items        jsonb,
  p_nombre       text,
  p_email        text,
  p_entrega      public.entrega_pedido,
  p_metodo_pago  public.metodo_pago_pedido,
  p_direccion    text   default null,
  p_comuna       text   default null,
  p_reserva_id   bigint default null,
  p_telefono     text   default null
)
  returns table (
    pedido_id    bigint,
    codigo       text,
    subtotal     integer,
    costo_envio  integer,
    descuento    integer,
    total        integer
  )
  language plpgsql
  security definer
  set search_path = public, pg_temp
as $$
#variable_conflict use_column
declare
  -- Reglas de dinero. Espejo en pedido.reglas.ts.
  c_costo_despacho    constant integer := 3990;
  c_umbral_gratis     constant integer := 40000;
  c_descuento_combo   constant numeric := 0.15;
  c_max_lineas        constant integer := 30;

  v_uid               uuid := auth.uid();
  v_servicio_cita     bigint;
  v_comuna_norm       text;
  v_codigo            text;
  v_pedido_id         bigint;
  v_subtotal          integer := 0;
  v_descuento         integer := 0;
  v_envio             integer := 0;
  v_linea             record;
begin
  -- --- Contacto -------------------------------------------------------------
  if nullif(btrim(coalesce(p_nombre, '')), '') is null then
    raise exception 'Necesitamos tu nombre para el pedido.' using errcode = 'P0001';
  end if;
  if coalesce(btrim(p_email), '') !~ '^[^@\s]+@[^@\s]+\.[^@\s]+$' then
    raise exception 'Revisa tu correo: lo necesitamos para avisarte del pedido.'
      using errcode = 'P0001';
  end if;

  -- --- Productos ------------------------------------------------------------
  if p_items is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'Tu carrito está vacío.' using errcode = 'P0001';
  end if;
  if jsonb_array_length(p_items) > c_max_lineas then
    raise exception 'El pedido tiene demasiadas líneas.' using errcode = 'P0001';
  end if;

  -- Se agrupa por slug: dos lineas del mismo producto suman cantidad en vez de
  -- saltarse el tope por linea.
  drop table if exists pg_temp._lineas;
  create temporary table _lineas on commit drop as
  select
    e ->> 'slug'                          as slug,
    sum((e ->> 'cantidad')::integer)      as cantidad
  from jsonb_array_elements(p_items) as e
  where coalesce(e ->> 'cantidad', '') ~ '^[0-9]{1,3}$'
  group by e ->> 'slug';

  if (select count(*) from _lineas) <> (
       select count(distinct e ->> 'slug') from jsonb_array_elements(p_items) e
     ) then
    raise exception 'Hay una cantidad no válida en el carrito.' using errcode = 'P0001';
  end if;
  if exists (select 1 from _lineas where cantidad < 1 or cantidad > 20) then
    raise exception 'Cada producto admite entre 1 y 20 unidades.' using errcode = 'P0001';
  end if;

  -- --- Entrega --------------------------------------------------------------
  if p_entrega = 'despacho' then
    if nullif(btrim(coalesce(p_direccion, '')), '') is null then
      raise exception 'Falta la dirección de despacho.' using errcode = 'P0001';
    end if;
    -- Cobertura: Viña del Mar y Valparaíso. Se compara sin tildes ni
    -- mayusculas, que es como la escribe la gente.
    v_comuna_norm := translate(lower(btrim(coalesce(p_comuna, ''))), 'áéíóúñ', 'aeioun');
    if v_comuna_norm not in ('vina del mar', 'valparaiso') then
      raise exception 'Por ahora despachamos solo en Viña del Mar y Valparaíso.'
        using errcode = 'P0001';
    end if;
    if p_metodo_pago = 'estudio' then
      raise exception 'Pagar en el estudio solo está disponible con retiro o entrega en tu cita.'
        using errcode = 'P0001';
    end if;
  elsif p_entrega = 'cita' then
    if v_uid is null then
      raise exception 'Inicia sesión para recibir el pedido en tu cita.' using errcode = 'P0001';
    end if;
    -- La reserva tiene que ser propia, futura y seguir viva.
    select r.servicio_id
      into v_servicio_cita
      from public.reservas r
     where r.id = p_reserva_id
       and r.cliente_id = v_uid
       and r.estado in ('pendiente', 'confirmada')
       and r.fecha >= (now() at time zone 'America/Santiago')::date;
    if not found then
      raise exception 'No encontramos una reserva vigente a tu nombre para entregar el pedido.'
        using errcode = 'P0001';
    end if;
  end if;

  -- --- Precios y stock ------------------------------------------------------
  if exists (
    select 1
      from _lineas l
      left join public.productos p on p.slug = l.slug and p.activo
     where p.id is null
  ) then
    raise exception 'Un producto de tu carrito ya no está disponible. Revisa el carrito.'
      using errcode = 'P0001';
  end if;

  -- FOR UPDATE bloquea las filas hasta el fin de la transaccion: dos compras
  -- simultaneas del ultimo kit no pueden pasar las dos.
  for v_linea in
    select l.slug, l.cantidad, p.id, p.nombre, p.precio, p.stock,
           p.categoria, p.servicio_id
      from _lineas l
      join public.productos p on p.slug = l.slug
     order by p.id
       for update of p
  loop
    if v_linea.stock is not null and v_linea.stock < v_linea.cantidad then
      raise exception 'No nos queda stock suficiente de %.', v_linea.nombre
        using errcode = 'P0001';
    end if;
    v_subtotal := v_subtotal + v_linea.precio * v_linea.cantidad;
    -- Combo: 15 % en los kits vinculados al servicio de la cita.
    if p_entrega = 'cita' and v_linea.categoria = 'kits'
       and v_linea.servicio_id is not null and v_linea.servicio_id = v_servicio_cita then
      v_descuento := v_descuento + round(v_linea.precio * v_linea.cantidad * c_descuento_combo)::integer;
    end if;
  end loop;

  if p_entrega = 'despacho' and v_subtotal < c_umbral_gratis then
    v_envio := c_costo_despacho;
  end if;

  -- --- Codigo ---------------------------------------------------------------
  loop
    v_codigo := 'NV-P-' || lpad((floor(random() * 1000000))::integer::text, 6, '0');
    exit when not exists (select 1 from public.pedidos x where x.codigo = v_codigo);
  end loop;

  -- --- Escritura ------------------------------------------------------------
  insert into public.pedidos as p (
    codigo, cliente_id, cliente_nombre, cliente_email, cliente_telefono,
    entrega, direccion, comuna, reserva_id, metodo_pago,
    subtotal, costo_envio, descuento, total
  )
  values (
    v_codigo, v_uid, btrim(p_nombre), lower(btrim(p_email)), nullif(btrim(coalesce(p_telefono, '')), ''),
    p_entrega,
    case when p_entrega = 'despacho' then btrim(p_direccion) end,
    case when p_entrega = 'despacho' then btrim(p_comuna) end,
    case when p_entrega = 'cita' then p_reserva_id end,
    p_metodo_pago,
    v_subtotal, v_envio, v_descuento, v_subtotal + v_envio - v_descuento
  )
  returning p.id into v_pedido_id;

  insert into public.pedido_items (pedido_id, producto_id, nombre, precio_unitario, cantidad, descuento)
  select
    v_pedido_id, p.id, p.nombre, p.precio, l.cantidad,
    case
      when p_entrega = 'cita' and p.categoria = 'kits'
           and p.servicio_id is not null and p.servicio_id = v_servicio_cita
        then round(p.precio * l.cantidad * c_descuento_combo)::integer
      else 0
    end
  from _lineas l
  join public.productos p on p.slug = l.slug;

  update public.productos p
     set stock = p.stock - l.cantidad
    from _lineas l
   where p.slug = l.slug
     and p.stock is not null;

  return query
  select v_pedido_id, v_codigo, v_subtotal, v_envio, v_descuento,
         v_subtotal + v_envio - v_descuento;
end;
$$;

comment on function public.crear_pedido is
  'Crea un pedido calculando precios, despacho y descuentos en la base. Unica via '
  'de escritura de pedidos y pedido_items.';

revoke all on function public.crear_pedido(
  jsonb, text, text, public.entrega_pedido, public.metodo_pago_pedido, text, text, bigint, text
) from public;
grant execute on function public.crear_pedido(
  jsonb, text, text, public.entrega_pedido, public.metodo_pago_pedido, text, text, bigint, text
) to anon, authenticated;

-- ----------------------------------------------------------------------------
-- suscribir_newsletter
-- ----------------------------------------------------------------------------
-- Idempotente y muda: suscribir un correo ya registrado responde igual que uno
-- nuevo, para no revelar quien esta suscrito.
create or replace function public.suscribir_newsletter(p_email text)
  returns void
  language plpgsql
  security definer
  set search_path = public, pg_temp
as $$
declare
  v_email text := lower(btrim(coalesce(p_email, '')));
begin
  if v_email !~ '^[^@\s]+@[^@\s]+\.[^@\s]+$' or length(v_email) > 254 then
    raise exception 'Revisa tu correo.' using errcode = 'P0001';
  end if;

  insert into public.suscripciones_newsletter (email)
  values (v_email)
  on conflict (email) do nothing;
end;
$$;

revoke all on function public.suscribir_newsletter(text) from public;
grant execute on function public.suscribir_newsletter(text) to anon, authenticated;

-- ----------------------------------------------------------------------------
-- Catalogo inicial
-- ----------------------------------------------------------------------------
-- Los 10 productos de la especificacion.
--
-- El servicio vinculado se busca por patrones en orden de prioridad, no por un
-- nombre fijo: el catalogo real ya no coincide con seed.sql («Esculpido de
-- Uñas» paso a ser «Extenciones en poligel», y no hay servicio facial). Gana el
-- primer patron que encuentre un servicio activo; si ninguno encuentra, el
-- producto queda sin vinculo en vez de fallar. Se puede corregir despues desde
-- el dashboard con un UPDATE de servicio_id.
insert into public.productos
  (slug, nombre, categoria, tamano, precio, precio_anterior, insignia, servicio_id,
   descripcion, modo_uso, ingredientes, orden)
select
  v.slug, v.nombre, v.categoria, v.tamano, v.precio, v.precio_anterior, v.insignia,
  (select s.id
     from unnest(v.servicio) with ordinality as patron (texto, prioridad)
     join public.servicios s on s.activo and s.nombre ilike patron.texto
    order by patron.prioridad, s.id
    limit 1),
  v.descripcion, v.modo_uso, v.ingredientes, v.orden
from (
  values
    ('aceite-de-cuticula-nura', 'Aceite de cutícula Nura', 'unas_manos', '15 ml', 9900, null::integer, 'mas_vendido', array['Manicura Completa', '%manicur%'],
     'El mismo aceite con que terminamos cada manicure. Nutre la cutícula y devuelve flexibilidad a la lámina en pocos días de uso.',
     'Una gota por uña cada noche. Masajea hasta absorber.',
     'Aceite de jojoba, almendras dulces, vitamina E.', 10),
    ('crema-de-manos-reparadora', 'Crema de manos reparadora', 'unas_manos', '75 ml', 12900, null, null, array['Manicura Completa', '%manicur%'],
     'Textura ligera que se absorbe rápido y no deja las manos grasosas. Pensada para lavados frecuentes.',
     'Aplica después de cada lavado y antes de dormir.',
     'Manteca de karité, glicerina, pantenol.', 20),
    ('fortalecedor-de-unas', 'Fortalecedor de uñas', 'unas_manos', '12 ml', 11900, null, null, array['Esculpido de Uñas', '%esculp%', '%poligel%', '%softgel%'],
     'Base tratante para uñas que se quiebran o descaman, ideal entre servicios de esculpido.',
     'Dos capas, dos veces por semana.',
     'Queratina hidrolizada, calcio, biotina.', 30),
    ('champu-reconstructor', 'Champú reconstructor', 'cabello', '250 ml', 16900, null, 'nuevo', array['Tratamiento Capilar', '%capilar%'],
     'Limpieza suave sin sulfatos para cabello procesado. Mantiene el resultado del tratamiento reconstructivo.',
     'Aplica sobre cabello húmedo, masajea y enjuaga.',
     'Proteína de trigo, aminoácidos, aloe vera.', 40),
    ('mascarilla-reparacion-profunda', 'Mascarilla de reparación profunda', 'cabello', '200 ml', 19900, null, null, array['Tratamiento Capilar', '%capilar%'],
     'Tratamiento semanal que sella la cutícula y devuelve brillo y suavidad.',
     'Una vez por semana, 10 minutos de medios a puntas.',
     'Ceramidas, aceite de argán, queratina.', 50),
    ('serum-cuero-cabelludo', 'Sérum para cuero cabelludo', 'cabello', '30 ml', 24900, null, null, array['Diagnóstico Capilar', '%diagn%capilar%', 'Tratamiento Capilar', '%capilar%'],
     'Equilibra y calma el cuero cabelludo. Recomendado después del diagnóstico capilar.',
     'Cinco gotas por zona sobre cuero cabelludo seco, sin enjuagar.',
     'Niacinamida, romero, péptidos.', 60),
    ('gel-limpiador-suave', 'Gel limpiador suave', 'piel', '150 ml', 15900, null, null, array['Tratamiento Facial', '%facial%', '%limpieza%'],
     'Limpia sin tirantez. El primer paso de la rutina que recomendamos tras una limpieza facial.',
     'Mañana y noche sobre piel húmeda.',
     'Ácido hialurónico, centella asiática.', 70),
    ('protector-solar-fps-50', 'Protector solar FPS 50', 'piel', '50 ml', 18900, null, null, array['Tratamiento Facial', '%facial%', '%limpieza%'],
     'Fluido invisible de uso diario, apto para piel sensible.',
     'Aplica 15 minutos antes de exponerte. Reaplica cada 3 horas.',
     'Filtros minerales, niacinamida.', 80),
    ('kit-ritual-manos', 'Kit Ritual Manos en casa', 'kits', 'Aceite + crema + lima', 29900, 34700, 'kit', array['Manicura Completa', '%manicur%'],
     'Todo lo necesario para mantener tu manicure entre citas, en una caja de regalo.',
     'Lima, aceite cada noche y crema después de cada lavado.',
     'Incluye Aceite de cutícula, Crema reparadora y lima de vidrio.', 90),
    ('gift-card-estudio-nura', 'Gift card Estudio Nura', 'gift_cards', 'Válida para servicios y productos', 25000, null, null, array[]::text[],
     'Regala un ritual o productos del estudio. Se envía por correo y vence en 12 meses.',
     'Se canjea al reservar o al pagar en la tienda.',
     '', 100)
) as v (slug, nombre, categoria, tamano, precio, precio_anterior, insignia, servicio,
        descripcion, modo_uso, ingredientes, orden)
on conflict (slug) do nothing;

-- Comprobacion: productos cargados y cuantos quedaron vinculados a un servicio.
select
  count(*)                                  as productos,
  count(servicio_id)                        as con_servicio,
  count(*) filter (where activo)            as activos
from public.productos;

notify pgrst, 'reload schema';
